name = "LrcFormalization"
version = "0.1.0"
defaultTargets = ["LrcFormalization"]

[[lean_lib]]
name = "LrcFormalization"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.33.1"
